server:
  port: 9200
spring:
  application:
    name: user-auth
  redis:
    host: 43.142.28.107
    port: 6379
    password: '0519'
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.28.107:3306/petsAdoption_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 20010519Smxy
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 43.142.28.107:8848

auth:
  ttl: 3600  #token存储到redis的过期时间  一小时
  clientId: petsAdoption
  clientSecret: petsAdoption
  cookieDomain: localhost
  cookieMaxAge: 3600
encrypt:
  key-store:
    location: classpath:/petsAdoption.jks
    secret: petsAdoption
    alias: petsAdoption
    password: petsAdoption

dubbo:
  protocol:    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1  #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
  registry:
    #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    address: spring-cloud://43.142.28.107:8848
  cloud:
    subscribed-services: user  # 订阅的提供者名称
  consumer:
    check: false  #关闭订阅服务是否启动的检查【检查时，没有服务提供者会报错】
